// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srnbylbbsdckkwatfqjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybmJ5bGJic2Rja2t3YXRmcWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODk1MTgsImV4cCI6MjA3MjY2NTUxOH0.CV_iKTlkbO8hr00GRPP4vaphSB8GVxYbsRC9_dlrfvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});